# This is a basic workflow to help you get started with Actions

name: flawfinder

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install falwfinder
      run: apt-get install flawfinder

    # Runs a set of commands using the runners shell
    - name: check flaws
      run: |
        echo checking flaws in your all c/cpp codes
        flawfinder -HCc . > flawfinder.html
    - name: Commit files
      run: |
        git add flawfinder.html
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "flawfinder report added" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
