on: push
name: Slack Notification 
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
         SLACK_CHANNEL: deep
         SLACK_COLOR: '#3278BD'
         SLACK_ICON: https://github.com/rtCamp.png?size=48
         SLACK_MESSAGE: 'dumb-server has benn updatet :rocket:'
         SLACK_TITLE: slack-noify
         SLACK_USERNAME: deep5050
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
